# Generated by Django 3.1 on 2021-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
